### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by pixx1** [Zhenye-Na/image-similarity-using-deep-ranking#10]
Hi there,
I'm a bit confused. How could I use (inference) my trained model after training?
When I load my trained model and set it in eval mode, how could I generated my vector for a single image?
Thanks!
pix_1

**Comment by ajsirsik** [comment]
Hello there,

Many thanks @Zhenye-Na  for sharing such a challenging and interesting project. It helped me as reference for my work. May I know how to test trained model after training ?

Thanks in advance 
with best regards

**Comment by Zhenye-Na** [comment]
pls have a look at Hasseb's recent pull request. https://github.com/Zhenye-Na/image-similarity-using-deep-ranking/pull/12

closed for now.
