### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by Zhenye-Na** [Zhenye-Na/image-similarity-using-deep-ranking#2]
@hodaatef

Try have a look at resources below:

https://github.com/sksq96/pytorch-summary/issues/16

and

```python
device = torch.device('cuda:0' if torch.cuda.is_avaliable() else 'cpu')

model.to(device)
```

From the error message it is because your model is not trained on GPU

**Comment by hodaatef** [comment]
Thank you for your concern

 """
    print("==> Start training ...")

    net.train()
    for epoch in range(start_epoch, epochs + start_epoch):

        running_loss = 0.0
        for batch_idx, (data1, data2, data3) in enumerate(trainloader):

            if is_gpu:
                device = torch.device("cuda" if torch.cuda.is_avaliable() else "cpu")
                data1, data2, data3 = data1.to(device), data2.to(device), data3.to(device)
            # wrap in torch.autograd.Variable
            data1, data2, data3 = Variable(
                data1), Variable(data2), Variable(data3)

            # compute output and loss
            embedded_a, embedded_p, embedded_n = net(data1, data2, data3)
            loss = criterion(embedded_a, embedded_p, embedded_n)

this is my code after update
is it true ?

**Comment by Zhenye-Na** [comment]
It looks good. Could you give a try?

Please feel free to reach out if you still have that error message. ^_^

**Comment by hodaatef** [comment]
```
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>
```

**Comment by hodaatef** [comment]
^_^

i have another message error :(

```
==> Initialize CUDA support for TripletNet model ...
==> Building new TripletNet model ...
==> Preparing Tiny ImageNet dataset ...
==> Start training ...
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 107, in main
    testloader, args.start_epoch, args.epochs, args.is_gpu)
  File "D:\deep-ranking\model7\utils.py", line 99, in train
    device = torch.device('cuda:0' if torch.cuda.is_avaliable() else 'cpu')
AttributeError: module 'torch.cuda' has no attribute 'is_avaliable'
```

**Comment by Zhenye-Na** [comment]
Did you

```python
import torch.cuda
```

See https://github.com/pytorch/pytorch/issues/283

**Comment by hodaatef** [comment]
yes ,
i  searched on Same page and other pages but i still have the same problem

**Comment by hodaatef** [comment]
```
(deep-ranking) D:\deep-ranking\model7>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch.nn as nn
>>> torch.cuda.is_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'torch' is not defined
>>> import torch.cuda
>>> torch.cuda.is_available()
True
>>>
```

**Comment by hodaatef** [comment]
the problem solved
but training loss 0.0 

```
(deep-ranking) D:\deep-ranking\model7>python main.py
==> Initialize CUDA support for TripletNet model ...
==> Building new TripletNet model ...
==> Preparing Tiny ImageNet dataset ...
==> Start training ...
Training Epoch: 1 | Loss: 0.0
Training Epoch: 2 | Loss: 0.0
Training Epoch: 3 | Loss: 0.0
```

why loss 0.0 ?? what is the problem

**Comment by Zhenye-Na** [comment]
Did you re-generate triplets of pics or use the `.txt` file in this repo? In my own experiment, the `log.txt` file contains all the training process output. Did you change any parameters? Have you met this issue all the time? 🤔

**Comment by hodaatef** [comment]
yes , i generate new triplets of pics,
i dont made any change of parameters :(

**Comment by Zhenye-Na** [comment]
Have you already solved this problem? I cannot help you tuning parameters for the loss currently since I do not have a GPU to run on my laptop. 🤔

**Comment by hodaatef** [comment]
A problem still exists :(
I am working on solving it

**Comment by Zhenye-Na** [comment]
So the training loss is still `0` ? Did you double check the triplets of image (the generated `txt` file)? Is it reasonable?

**Comment by hodaatef** [comment]
yes still 0...
i checked it  , the same with your triplets.txt

**Comment by hodaatef** [comment]
i think the problem is overfitting
weights overfit with datasets
but how i solve this problems

**Comment by hodaatef** [comment]
i solved the problem but loss very high 
???
i decreased batch size but loss still very high 
training take long time many hours to produce first loss ??

==> Initialize CUDA support for TripletNet model ...
==> Building new TripletNet model ...
==> Preparing Tiny ImageNet dataset ...
==> Start training ...
Training Epoch: 1 | Loss: 23767.899179816246

**Comment by hodaatef** [comment]
i solved the problem
thanks for your concern

**Comment by Zhenye-Na** [comment]
Glad to hear this. ~

**Comment by miege2k** [comment]
Hey I have the same problem but this code is not working for me.
 
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
data1, data2, data3 = data1.to(device), data2.to(device), data3.to(device)
```

Have you any idea what the problem is?

**Comment by miege2k** [comment]
So now I fixed the problem. The right code is this(utils.py(91)):
```
print("==> Start training ...")
net.train()
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
net.to(device)
```

**Comment by ajsirsik** [comment]
> the problem solved
> but training loss 0.0
> 
> ```
> (deep-ranking) D:\deep-ranking\model7>python main.py
> ==> Initialize CUDA support for TripletNet model ...
> ==> Building new TripletNet model ...
> ==> Preparing Tiny ImageNet dataset ...
> ==> Start training ...
> Training Epoch: 1 | Loss: 0.0
> Training Epoch: 2 | Loss: 0.0
> Training Epoch: 3 | Loss: 0.0
> ```
> 
> why loss 0.0 ?? what is the problem

Hello @hodaatef 

Hope you're doing well 
May I know how did you resolve "AttributeError: module 'torch.cuda' has no attribute 'is_avaliable'"

Thanks in advance

**Comment by YgluWanh** [comment]
unfinished
