### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (100000,128) (200000,128)

### ISSUE THREAD

**Issue by hodaatef** [Zhenye-Na/image-similarity-using-deep-ranking#7]
why this error?
==> Preparing Tiny ImageNet dataset ...
==> Retrieve model parameters ...
Get all test image classes, Done ... | Time elapsed 0.014259099960327148s
Get all training images, Done ... | Time elapsed 0.10345053672790527s
Get embedded_features, Done ... | Time elapsed 5874.124089002609s
Now processing 0th test image
Traceback (most recent call last):
  File "D:\deep-ranking\model7\accuracy.py", line 206, in <module>
    main()
  File "D:\deep-ranking\model7\accuracy.py", line 202, in main
    calculate_accuracy(trainloader, testloader, args.is_gpu)
  File "D:\deep-ranking\model7\accuracy.py", line 115, in calculate_accuracy
    embedding_diff = embedded_features_train - embedded_features_test
ValueError: operands could not be broadcast together with shapes (100000,128) (200000,128)

**Comment by miege2k** [comment]
i have the same error

**Comment by lululalamm** [comment]
i hv too
